baseurl = "https://iamavneetsk.cf/"
title = "Avneet Singh"
theme = "newsroom"
author = "IamAvneetSK"
copyright = "Copyright © 2021, IamAvneetSK; All Rights Reserved."
canonifyurls = true
paginate = 6
params = { }
themesDir = "themes"
baseURL = ""
publishDir = "public"

[markup.goldmark.renderer]
hardWraps = false
unsafe = false
xhtml = false

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = false
tabWidth = 2
